name: Build and Deploy
on:
  push:
    branches:
      - main
permissions:
  contents: write
  pages: write
jobs:
  run-eslint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v4

      - name: Configure Node
        uses: actions/setup-node@v1
        with:
          node-version: '20'

      - name: Run Install 
        run: |
          npm ci
          
      - name: Run ESLint ğŸ”
        run: npm run lint
    
  build-and-deploy:
    concurrency: ci-${{ github.ref }} # Recommended if you intend to make multiple deployments in quick succession.
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v4

      - name: Configure Node
        uses: actions/setup-node@v1
        with:
          node-version: '20'

      - name: Install and Build ğŸ”§ # This example project is built using npm and outputs the result to the 'build' folder. Replace with the commands required to build your project, or remove this step entirely if your site is pre-built.
        run: |
          npm ci
          npm run build

      - name: Upload to S3 ğŸš€
        uses: Jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read
        env:
          SOURCE_DIR: build/
          AWS_S3_BUCKET: ${{secrets.AWS_S3_BUCKET}}
          AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
